-- Imágenes de productos (generado por seed-product-images.js)
-- Ejecutar después de datos_prueba.sql en inicializaciones limpias de Docker.

UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238697/tacos-el-pepe/productos/taco-al-pastor-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-al-pastor-seed' WHERE nombre = 'Taco al Pastor';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238697/tacos-el-pepe/productos/taco-de-bistec-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-de-bistec-seed' WHERE nombre = 'Taco de Bistec';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238698/tacos-el-pepe/productos/taco-de-chorizo-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-de-chorizo-seed' WHERE nombre = 'Taco de Chorizo';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238698/tacos-el-pepe/productos/taco-de-lengua-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-de-lengua-seed' WHERE nombre = 'Taco de Lengua';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238699/tacos-el-pepe/productos/taco-de-pollo-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-de-pollo-seed' WHERE nombre = 'Taco de Pollo';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238700/tacos-el-pepe/productos/taco-vegetariano-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-vegetariano-seed' WHERE nombre = 'Taco Vegetariano';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238701/tacos-el-pepe/productos/taco-campechano-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-campechano-seed' WHERE nombre = 'Taco Campechano';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238701/tacos-el-pepe/productos/taco-gringa-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-gringa-seed' WHERE nombre = 'Taco Gringa';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238775/tacos-el-pepe/productos/taco-dorado-de-pollo-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-dorado-de-pollo-seed' WHERE nombre = 'Taco Dorado de Pollo';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242924/tacos-el-pepe/productos/taco-de-suadero-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-de-suadero-seed' WHERE nombre = 'Taco de Suadero';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238777/tacos-el-pepe/productos/taco-especial-del-pepe-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-especial-del-pepe-seed' WHERE nombre = 'Taco Especial del Pepe';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238777/tacos-el-pepe/productos/taco-de-cochinita-pibil-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/taco-de-cochinita-pibil-seed' WHERE nombre = 'Taco de Cochinita Pibil';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242333/tacos-el-pepe/productos/horchata-grande-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/horchata-grande-seed' WHERE nombre = 'Horchata Grande';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242334/tacos-el-pepe/productos/agua-de-jamaica-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/agua-de-jamaica-seed' WHERE nombre = 'Agua de Jamaica';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242334/tacos-el-pepe/productos/coca-cola-seed.webp', imagen_public_id = 'tacos-el-pepe/productos/coca-cola-seed' WHERE nombre = 'Coca-Cola';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238706/tacos-el-pepe/productos/agua-pura-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/agua-pura-seed' WHERE nombre = 'Agua Pura';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238707/tacos-el-pepe/productos/limonada-con-chia-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/limonada-con-chia-seed' WHERE nombre = 'Limonada con Chía';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238708/tacos-el-pepe/productos/cafe-de-olla-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/cafe-de-olla-seed' WHERE nombre = 'Café de Olla';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242337/tacos-el-pepe/productos/combo-clasico-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-clasico-seed' WHERE nombre = 'Combo Clásico';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242338/tacos-el-pepe/productos/combo-familiar-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-familiar-seed' WHERE nombre = 'Combo Familiar';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242339/tacos-el-pepe/productos/combo-del-pepe-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-del-pepe-seed' WHERE nombre = 'Combo del Pepe';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242340/tacos-el-pepe/productos/combo-vegetariano-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-vegetariano-seed' WHERE nombre = 'Combo Vegetariano';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242340/tacos-el-pepe/productos/combo-pareja-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-pareja-seed' WHERE nombre = 'Combo Pareja';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242341/tacos-el-pepe/productos/combo-ejecutivo-seed.webp', imagen_public_id = 'tacos-el-pepe/productos/combo-ejecutivo-seed' WHERE nombre = 'Combo Ejecutivo';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242342/tacos-el-pepe/productos/combo-picante-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-picante-seed' WHERE nombre = 'Combo Picante';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242343/tacos-el-pepe/productos/combo-postre-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-postre-seed' WHERE nombre = 'Combo Postre';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242344/tacos-el-pepe/productos/combo-desayuno-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/combo-desayuno-seed' WHERE nombre = 'Combo Desayuno';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242345/tacos-el-pepe/productos/flan-napolitano-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/flan-napolitano-seed' WHERE nombre = 'Flan Napolitano';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779238791/tacos-el-pepe/productos/churros-con-chocolate-seed.jpg', imagen_public_id = 'tacos-el-pepe/productos/churros-con-chocolate-seed' WHERE nombre = 'Churros con Chocolate';
UPDATE producto SET imagen_url = 'https://res.cloudinary.com/dku354y0m/image/upload/v1779242346/tacos-el-pepe/productos/arroz-con-leche-seed.webp', imagen_public_id = 'tacos-el-pepe/productos/arroz-con-leche-seed' WHERE nombre = 'Arroz con Leche';
